### ISSUE TITLE
landing page

### ISSUE THREAD

**Issue by farahccino** [farahccino/capstone-project-cherish#1]
## Value Statement
As a user I want to be greeted by the app and get asked about my current mood.

## Description
<img width="130" alt="01-landing" src="https://user-images.githubusercontent.com/80906106/120892546-33c09400-c60f-11eb-93ab-ab9216001f99.png">

## Acceptance Criteria
- [x] the app greets the user
- [x] the user can express their current mood by selecting one emoji out of five
- [x] the mood gets saved so that the user can look back and track it

## Complexity
M

## Tasks
- [x] new feature branch 'landing-page'
- [x] add greeting
- [x] add emojis 
- [x] save emojis to daily key in localStorage
- [x] redirect to home page after clicking emoji
