### ISSUE TITLE
edit goals

### ISSUE THREAD

**Issue by farahccino** [farahccino/capstone-project-cherish#14]
## Value Statement
As a user I want to be able to edit and delete my goals.

## Description
<img width="148" alt="06-edit and delete goals" src="https://user-images.githubusercontent.com/80906106/123270573-518f6380-d500-11eb-8d73-6acec2e49cf9.png">

## Acceptance Criteria 
- [x] clicking on the goal should open a modal with the habit form
- [x] the modal allows the user to edit the goal and the frequency
- [x] the user can delete the goal
- [x] the user can also abort the editing process and return to the goal page

## Complexity
L

## Tasks
- [x] new feature branch 'goal-page' 
- [x] link to form by clicking on each goal
- [x] embed modal
- [x] implement editing and delete functions
- [x] add return button
