### ISSUE TITLE
tracker

### ISSUE THREAD

**Issue by farahccino** [farahccino/capstone-project-cherish#15]
## Value Statement
As a user I want to be able to track my goals and analyze my productivity. I also want to be able to speculate about the correlation between my productivity and daily mood. 

## Description
<img width="265" alt="03-tracker" src="https://user-images.githubusercontent.com/80906106/123271643-57397900-d501-11eb-8d5f-475788dddeb2.png">

## Acceptance Criteria 
- [x] the tracker displays the weekly activity and mood
- [x] the user can see which daily tasks have been completed over the span of a week

## Complexity
XXL

## Tasks
- [x] new feature branch 'tracker' 
- [x] display a grid
- [x] load mood from localStorage of landing page
- [x] load daily habits from localStorage of home page
