### ISSUE TITLE
today page

### ISSUE THREAD

**Issue by farahccino** [farahccino/capstone-project-cherish#2]
## Value Statement
As a user I want to view my daily goals and select the ones I fulfilled.

## Description
<img width="283" alt="02-today" src="https://user-images.githubusercontent.com/80906106/120893240-88194300-c612-11eb-8726-28e8a93f11bd.png">

## Acceptance Criteria
- [x] user can view the daily goals they defined themselves
- [x] user can check each achieved goal
- [x] user can uncheck each achieved goal
- [x] daily achieved goals get saved
- [x] user navigates to tracker page by clicking on the button
- [x] user navigates to edit page by clicking on the pen

## Complexity
L

## Tasks
- [x] new feature branch 'today-page'
- [x] add checkbox component
- [x] implement checkbox logic
- [x] save to localStorage 
- [x] add button that navigates to the tracker page
- [x] add button that navigates to the edit page
