### ISSUE TITLE
edit today page

### ISSUE THREAD

**Issue by farahccino** [farahccino/capstone-project-cherish#3]
## Value Statement
As a user I want to be able to add goals and define their frequency. I also want to be able to edit and delete my goals.

## Description
<img width="225" alt="02 5-edit today" src="https://user-images.githubusercontent.com/80906106/120979682-2245cc00-c776-11eb-93e8-c9a2fdc8087d.png">

## Acceptance Criteria 
- [x] clicking on the pen button opens the edit form
- [x] clicking on the delete icon removes the goal

## Complexity
M

## Tasks
- [x] new feature branch 'edit-today-page' 
- [x] link to form by clicking on pen
- [x] delete function
