### ISSUE TITLE
footer navigation

### ISSUE THREAD

**Issue by farahccino** [farahccino/capstone-project-cherish#4]
## Value Statement
As a user I want to be able to navigate through the app by clicking on the icons.

## Description
<img width="231" alt="09-footer-navigation" src="https://user-images.githubusercontent.com/80906106/121158801-ed577900-c84a-11eb-9f8f-d266200885a2.png">

## Acceptance Criteria 
- [x] clicking on the left icon opens the today page
- [x] clicking on the right icon opens the goal page
- [x] clicking on the plus icon opens the add-goal page

## Complexity
S

## Tasks
- [x] new feature branch 'footer-navigation' 
- [x] link to today page
- [x] link to form to add a goal
- [x] link to goal page
- [x] add icons
- [x] add tests
- [x] add styleguidist component
