### ISSUE TITLE
design

### ISSUE THREAD

**Issue by farahccino** [farahccino/capstone-project-cherish#5]
## Value Statement
As a user I want to use an app with a beautiful design.

## Description
<img width="649" alt="Bildschirmfoto 2021-06-08 um 15 01 17" src="https://user-images.githubusercontent.com/80906106/121189417-62867680-c86a-11eb-98e1-4203101458fa.png">

## Acceptance Criteria 
- [x] nice logo
- [x] nice icons
- [x] nice color scheme
- [x] positive feeling when using the app

## Complexity
L

## Tasks
- [x] add logo
- [x] add icons
- [x] add color scheme
- [x] animated background
- [x] icon on each button
- [x] svg change depending on page
- [x] bug fixes
