### ISSUE TITLE
add a daily goal

### ISSUE THREAD

**Issue by farahccino** [farahccino/capstone-project-cherish#7]
## Value Statement
As a user I want to be able to add a new goal to my list of daily habits. 

## Description
<img width="135" alt="04-add goal" src="https://user-images.githubusercontent.com/80906106/121692810-c4441c00-cac8-11eb-8d51-cdddeacdef59.png">
<img width="132" alt="0401-drop-down" src="https://user-images.githubusercontent.com/80906106/121692835-c8703980-cac8-11eb-8cb2-75481f52feb2.png">

## Complexity
L

## Acceptance Criteria
- [x] The user can submit the form by clicking on a submit button
- [x] The user can clear the form by clicking on a cancel button

## Tasks
- [x] Open up new branch "plus-page"
- [x] Create a new form component
- [x] Save the new habit in an array/useState
- [x] Add validation 
- [x] Add propTypes
