### ISSUE TITLE
goal page

### ISSUE THREAD

**Issue by farahccino** [farahccino/capstone-project-cherish#8]
## Value Statement
As a user I want to have an overview over my goals.

## Description
<img width="135" alt="05-goals" src="https://user-images.githubusercontent.com/80906106/121817598-a9b5a280-cc82-11eb-9322-000824ab434a.png">

## Acceptance Criteria
- [x] user can view the goals they defined themselves
- [x] user can view the frequency of said goals
- [x] user can edit the goals by clicking on the pen

## Complexity
M

## Tasks
- [x] new feature branch 'goal-page'
- [x] add table that displays the defined goals
- [x] add button that navigates to the edit page
